[2025-01-16 15:37:37,001][modelflow.modelflow.__main__][DEBUG] - DEBUG ENABLED
[2025-01-16 15:37:37,001][modelflow.__main__][INFO] - Launch command: ['/home/kuhmichel/anaconda3/envs/eki/bin/modelflow', 'debug=True', 'run=manuelsequence']
[2025-01-16 15:37:37,001][modelflow.__main__][INFO] - Storing run config in global...
[2025-01-16 15:37:37,001][modelflow.__main__][DEBUG] - config:
[2025-01-16 15:37:37,001][modelflow.__main__][DEBUG] - {'debug': True, 'run': {'_target_': 'modelflow.run.ManuelSequence', 'tasks': [{'_target_': 'modelflow.run.Sequence', 'cmd_args': 'run=train dataset=tsV2 dataset.dataloader.batch_size=2 tokenizer=hf tokenizer.encoding=fhswf/BPE_GPT2_TinyStoriesV2_cleaned_2048 run.epochs=1 tokenizer=hf_gptneo +model.type=CHECKPOINT  model=NEW_BENCH2 quantization=qat quantization/model=NEW_BENCH2b run.export=True', 'tasks': [{'cmd_args': '', '_target_': 'modelflow.command.QTransformCommand'}]}, {'_target_': 'modelflow.command.meta.Sequence', 'common_args': '', 'tasks': [{'cmd_args': '', 'type': 'modelflow.command.QTransformCommand'}, {'cmd_args': '', 'type': 'modelflow.command.QTransformCommand'}, {'cmd_args': '', 'type': 'modelflow.command.QTransformCommand'}, {'type': 'modelflow.command.meta.Paralell', 'commands': [{'cmd_args': '', 'type': 'modelflow.command.QTransformCommand'}, {'cmd_args': '', 'type': 'modelflow.command.QTransformCommand'}, {'cmd_args': '', 'type': 'modelflow.command.QTransformCommand'}]}, {'cmd_args': '', 'type': 'modelflow.command.QTransformCommand'}, {'cmd_args': '', 'type': 'modelflow.command.QTransformCommand'}]}]}, 'runtime': {'choices': {'run': 'manuelsequence', 'hydra/env': 'default', 'hydra/callbacks': None, 'hydra/job_logging': 'perlevel', 'hydra/hydra_logging': 'default', 'hydra/hydra_help': 'default', 'hydra/help': 'main', 'hydra/sweeper': 'basic', 'hydra/launcher': 'basic', 'hydra/output': 'default'}}}
[2025-01-16 15:37:37,006][modelflow.__main__][CRITICAL] - Script execution failed. Reason: Error in call to target 'modelflow.command.qtransform.QTransformCommand':
TypeError("QTransformCommand.__init__() missing 1 required positional argument: 'cmd_bin'")
full_key: run.tasks[0].tasks0
Traceback (most recent call last):
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
TypeError: QTransformCommand.__init__() missing 1 required positional argument: 'cmd_bin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/__main__.py", line 57, in main
    run = instantiate(cfg.run)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 316, in instantiate_node
    items = [
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 317, in <listcomp>
    instantiate_node(item, convert=convert, recursive=recursive)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 316, in instantiate_node
    items = [
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 317, in <listcomp>
    instantiate_node(item, convert=convert, recursive=recursive)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'modelflow.command.qtransform.QTransformCommand':
TypeError("QTransformCommand.__init__() missing 1 required positional argument: 'cmd_bin'")
full_key: run.tasks[0].tasks0
[2025-01-16 15:37:37,007][modelflow.__main__][ERROR] - Exited with Status Code: 1
